In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [3]:
df = pd.read_csv('Train.csv')
df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1

In [4]:
df.tail()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
10994,10995,A,Ship,4,1,252,5,medium,F,1,1538,1
10995,10996,B,Ship,4,1,232,5,medium,F,6,1247,0
10996,10997,C,Ship,5,4,242,5,low,F,4,1155,0
10997,10998,F,Ship,5,2,223,6,medium,M,2,1210,0
10998,10999,D,Ship,2,5,155,5,low,F,6,1639,0

In [5]:
df.describe()

,ID,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
count,10999.00000,10999.000000,10999.000000,10999.000000,10999.000000,10999.000000,10999.000000,10999.000000
mean,5500.00000,4.054459,2.990545,210.196836,3.567597,13.373216,3634.016729,0.596691
std,3175.28214,1.141490,1.413603,48.063272,1.522860,16.205527,1635.377251,0.490584
min,1.00000,2.000000,1.000000,96.000000,2.000000,1.000000,1001.000000,0.000000
25%,2750.50000,3.000000,2.000000,169.000000,3.000000,4.000000,1839.500000,0.000000
50%,5500.00000,4.000000,3.000000,214.000000,3.000000,7.000000,4149.000000,1.000000
75%,8249.50000,5.000000,4.000000,251.000000,4.000000,10.000000,5050.000000,1.000000
max,10999.00000,7.000000,5.000000,310.000000,10.000000,65.000000,7846.000000,1.000000

In [6]:
df.isnull().sum()

ID                     0
Warehouse_block        0
Mode_of_Shipment       0
Customer_care_calls    0
Customer_rating        0
Cost_of_the_Product    0
Prior_purchases        0
Product_importance     0
Gender                 0
Discount_offered       0
Weight_in_gms          0
Reached.on.Time_Y.N    0
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10999 entries, 0 to 10998
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   10999 non-null  int64
 1   Warehouse_block      10999 non-null  str
 2   Mode_of_Shipment     10999 non-null  str
 3   Customer_care_calls  10999 non-null  int64
 4   Customer_rating      10999 non-null  int64
 5   Cost_of_the_Product  10999 non-null  int64
 6   Prior_purchases      10999 non-null  int64
 7   Product_importance   10999 non-null  str
 8   Gender               10999 non-null  str
 9   Discount_offered     10999 non-null  int64
 10  Weight_in_gms        10999 non-null  int64
 11  Reached.on.Time_Y.N  10999 non-null  int64
dtypes: int64(8), str(4)
memory usage: 1.0 MB

In [8]:
num_col = ('Customer_care_calls', 'Customer_rating', 'Cost_of_the_Product', 'Prior_purchases', 'Discount_offered', 'Weight_in_gms')
iqr_summary = []

for col in num_col:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - (1.5 * IQR)
    upper_bound = Q3 + (1.5 * IQR)

    outlier_condition = (df[col] < lower_bound) | (df[col] > upper_bound)
    outlier_count = outlier_condition.sum()
    outlier_pct = (outlier_count / len(df)) * 100

    iqr_summary.append({
        'Feature': col,
        'Q1': Q1,
        'Q3': Q3,
        'IQR': IQR,
        'Lower Bound': lower_bound,
        'Upper Bound': upper_bound,
        'Outlier Count': outlier_count,
        'Outlier %': f"{outlier_pct:.2f}%"
    })

# Convert summary into a DataFrame
iqr_df = pd.DataFrame(iqr_summary)
print(iqr_df.to_string(index=False))

            Feature     Q1     Q3    IQR  Lower Bound  Upper Bound  Outlier Count Outlier %
Customer_care_calls    3.0    5.0    2.0         0.00         8.00              0     0.00%
    Customer_rating    2.0    4.0    2.0        -1.00         7.00              0     0.00%
Cost_of_the_Product  169.0  251.0   82.0        46.00       374.00              0     0.00%
    Prior_purchases    3.0    4.0    1.0         1.50         5.50           1003     9.12%
   Discount_offered    4.0   10.0    6.0        -5.00        19.00           2209    20.08%
      Weight_in_gms 1839.5 5050.0 3210.5     -2976.25      9865.75              0     0.00%

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

In [10]:

importance_mapping = {'low': 1, 'medium': 2, 'high': 3}
df['Product_importance'] = df['Product_importance'].map(importance_mapping)

df = pd.get_dummies(df, columns=['Warehouse_block', 'Mode_of_Shipment', 'Gender'], drop_first=True)

In [11]:
x = df.drop(columns=['ID', 'Reached.on.Time_Y.N'])
y = df['Reached.on.Time_Y.N']


x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.20, random_state=42, stratify=y
)

In [12]:
from sklearn.preprocessing import RobustScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

scaler = RobustScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled  = scaler.transform(x_test)

In [13]:
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [14]:
knn_model.score(x_train, y_train)

c:\Users\Miracle\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

0.5966587112171837

In [15]:

dt_model = DecisionTreeClassifier(max_depth=5, random_state=42)
dt_model.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [16]:
dt_model.score(x_train, y_train)

0.6915558586202978

In [17]:
dt_model.score(x_test, y_test)

0.6795454545454546

In [18]:
rf_model = RandomForestClassifier(n_estimators=200, max_depth=8, min_samples_split=5, min_samples_leaf=2, random_state=42)
rf_model.fit(x_train, y_train)

RandomForestClassifier(max_depth=8, min_samples_leaf=2, min_samples_split=5,
                       n_estimators=200, random_state=42)

In [19]:
rf_model.score(x_train, y_train)

0.7328105466530288

In [20]:
rf_model.score(x_test, y_test)

0.68

In [21]:
xgb_model = XGBClassifier(n_estimators=80, learning_rate=0.3, max_depth=2, min_child_weight=5, subsample=0.8, colsample_bytree=0.8, random_state=42, eval_metric='logloss')
xgb_model.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.3, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=80, n_jobs=None,
              num_parallel_tree=None, ...)

In [22]:
xgb_model.score(x_train, y_train)

0.7065575633594726

In [23]:
xgb_model.score(x_test, y_test)

0.6722727272727272

In [24]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [50, 60, 80],
    'max_depth': [2, 6, 8],
    'min_child_weight': [2, 5, 10],
    'subsample': [0.4, 0.6, 0.8]
}

grid_search = GridSearchCV(
    estimator=XGBClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=1
)

grid_search.fit(x_train, y_train)
best_xgb = grid_search.best_estimator_

print("Best Parameters:", grid_search.best_params_)
print("Optimized Test Accuracy:", best_xgb.score(x_test, y_test))

Best Parameters: {'max_depth': 2, 'min_child_weight': 2, 'n_estimators': 50, 'subsample': 0.8}
Optimized Test Accuracy: 0.6809090909090909

In [25]:
from sklearn.metrics import classification_report

In [26]:
y_pred = rf_model.predict(x_test)

In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.56      0.94      0.70       887
           1       0.93      0.50      0.65      1313

    accuracy                           0.68      2200
   macro avg       0.74      0.72      0.68      2200
weighted avg       0.78      0.68      0.67      2200

In [28]:
df['Reached.on.Time_Y.N'].value_counts()

Reached.on.Time_Y.N
1    6563
0    4436
Name: count, dtype: int64

In [29]:
# Undersampling the majority

df_values0 = df[df['Reached.on.Time_Y.N'] == 0]
df_values1 = df[df['Reached.on.Time_Y.N'] == 1]

In [30]:
count1, count0 = df['Reached.on.Time_Y.N'].value_counts()

In [31]:
count1

6563

In [32]:
dfvalues1_undersampled = df_values1.sample(count0)

In [33]:
dfvalues1_undersampled.shape

(4436, 16)

In [34]:
df_undersampled = pd.concat([dfvalues1_undersampled, df_values0], axis=0)

In [35]:
df_undersampled.shape

(8872, 16)

In [36]:
df_undersampled = df_undersampled.drop("ID", axis = 1)

In [37]:
X_under = df_undersampled.drop("Reached.on.Time_Y.N", axis=1)
y_under = df_undersampled['Reached.on.Time_Y.N']

In [38]:
X_under.head()

,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Discount_offered,Weight_in_gms,Warehouse_block_B,Warehouse_block_C,Warehouse_block_D,Warehouse_block_F,Mode_of_Shipment_Road,Mode_of_Shipment_Ship,Gender_M
2818,3,1,164,3,2,9,1803,False,True,False,False,False,True,False
2895,3,5,152,2,2,6,1800,True,False,False,False,False,True,False
8418,5,1,224,3,1,7,5870,False,False,True,False,False,True,True
1160,4,5,127,8,1,39,1411,False,False,False,False,False,True,True
7349,4,4,209,3,2,8,5884,False,False,False,True,False,True,True

In [39]:
X_train_under, X_test_under, y_train_under, y_test_under = train_test_split(X_under, y_under, test_size = 0.2, random_state= 42, stratify = y_under)

In [40]:
rf_model.fit(X_train_under, y_train_under)

RandomForestClassifier(max_depth=8, min_samples_leaf=2, min_samples_split=5,
                       n_estimators=200, random_state=42)

In [41]:
rf_model.score(X_train_under, y_train_under)

0.7470762293927011

In [42]:
rf_model.score(X_test_under, y_test_under)

0.7374647887323944

In [43]:
xgb_model.fit(X_train_under, y_train_under)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.3, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=80, n_jobs=None,
              num_parallel_tree=None, ...)

In [44]:
xgb_model.score(X_train_under, y_train_under)

0.7411582358743131

In [45]:
xgb_model.score(X_test_under, y_test_under)

0.7374647887323944

In [46]:
dt_model.fit(X_train_under, y_train_under)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [47]:
dt_model.score(X_train_under, y_train_under)

0.7372129068620544

In [48]:
dt_model.score(X_test_under, y_test_under)

0.7357746478873239

In [50]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Only 12 total combinations (60 fits with 5-fold CV)
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [6, 8, 12],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

rf_base = RandomForestClassifier(random_state=42)

grid_search = GridSearchCV(
    estimator=rf_base,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,          # Uses all CPU cores
    verbose=2           # Gives real-time progress updates in the output
)

grid_search.fit(X_train_under, y_train_under)

print("Best Parameters:", grid_search.best_params_)
print("Best CV Score:", grid_search.best_score_)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
Best Parameters: {'max_depth': 8, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Best CV Score: 0.7341140854996079

In [51]:
import joblib


best_rf_model = grid_search.best_estimator_ 

joblib.dump(best_rf_model, 'best_random_forest_model.pkl')
print("Model exported successfully!")

Model exported successfully!